name: Santa CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v2
      - name: Install local dependencies
        run: |
          npm install
          ./node_modules/.bin/elm-tooling install
      - name: Check formatting of source files
        run: ./node_modules/.bin/elm-format ./src ./tests --validate
      - name: Elm review
        run: ./node_modules/.bin/elm-review --compiler ./node_modules/.bin/elm
      - name: Run tests
        run: ./node_modules/.bin/elm-test-rs
