name: Santa CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install local dependencies
        run: |
          npm install
          npx elm-tooling install
      - name: Check formatting of source files
        run: npx elm-format ./src ./tests --validate
      - name: Elm review
        run: npx elm-review
      - name: Run tests
        run: npx elm-test
